  
services:
  mrp_db:
    image: postgres:16
    container_name: mrp_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mrp_db
    ports:
      - "5432:5432"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: